server:
  port: 9000
spring:

  profiles:
    active: "qa"

  datasource:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    username: user
    password: password
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


    build:
      version: "3.0"

    cards:
      message: "Welcome to the Cards microservice"
      contactInfo:
        name: "Cards Team"
        email: "cards@bank.com"
      onCallSupport:
        - "9943032698"
        - "6374526623"