spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Dharaneeshravi/config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest
#        native:
#          search-locations: "classpath:/config"
#           search-locations: "file:///C://Users//hanus//Documents//config"
  profiles:
#    active: native
     active: git
  application:
    name: "configserver"


encrypt:
  key: "A7mX9qLp2Nz4Hr8Kw1Ty5Df3Vc6Bs0Je"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071
